-- Add product_id column to sales table if it doesn't exist
ALTER TABLE sales 
ADD COLUMN IF NOT EXISTS product_id UUID REFERENCES products(id);

-- Optional: Create an index for better performance on joins
CREATE INDEX IF NOT EXISTS idx_sales_product_id ON sales(product_id);

-- Comment
COMMENT ON COLUMN sales.product_id IS 'Link to the products table (auto-generated by Sync)';
